config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users, path: '', controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }, path_names: { sign_up: 'sign_up', edit: 'edit_account'}

  devise_scope :user do
    post '/sign_up' => "users/registrations#create"
    patch '/edit_account' => "users/registrations#update"
    put '/edit_account' => "users/registrations#update"
  end

  get 'index' => 'pages#index'
  get 'home' => 'pages#index'
  get 'q/index' =>  redirect('/q')
  get 'u/index' =>  redirect('/u')

  resources :quota, path: 'q', param: :slug
  resources :users, path: 'u'

  get 'quota/index' => redirect('/q')
  get "/quota" => redirect('/q')
  get '/quota/new' => redirect('/q/new')
  get '/quota/:slug/edit', to: redirect("/q/%{slug}/edit")
  get '/quota/:slug/edit', to: redirect("/q/%{slug}/edit")

  get 'users/index' => redirect('/u')
  get '/users' => redirect('/u')

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-new navbar-fixed-top">
  <div class="container-no-padding">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="row row-no-padding">
      <div class="col-sm-5">
        <div class="collapse navbar-collapse">
          <%= render 'shared/navbar_partials/navbar_left' %>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="navbar-header-center">
          <div class="navbar-brand">
          <%= link_to home_path do %>
            <div class="triangle-inverse"><p>PS<span class="header-micro">&equiv;</span></p></div>
          <% end %>
          </div>
        </div>
      </div>

      <div class="col-sm-5">
        <div class="collapse navbar-collapse shift-padding-right-strong">
          <%= render 'shared/navbar_partials/navbar_right' %>
        </div><!-- /.navbar-collapse -->
      </div>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
  </div><!-- /.container -->
</nav>